// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8_gnkchNhFJRSlciwl-25nERVhA0xO8',
    appId: '1:802711499708:web:50ac8b17ebff17afb631b9',
    messagingSenderId: '802711499708',
    projectId: 'automotrizapp',
    authDomain: 'automotrizapp.firebaseapp.com',
    databaseURL: 'https://automotrizapp-default-rtdb.firebaseio.com',
    storageBucket: 'automotrizapp.firebasestorage.app',
    measurementId: 'G-Y01G3KVBLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDoAPa9lDpSaAZwmQ0RHn7a7M6gq7UCU',
    appId: '1:802711499708:android:75640bc14ff16f57b631b9',
    messagingSenderId: '802711499708',
    projectId: 'automotrizapp',
    databaseURL: 'https://automotrizapp-default-rtdb.firebaseio.com',
    storageBucket: 'automotrizapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PZG1yBdKgs6j6sEFV9CIxMYak_2T7q8',
    appId: '1:802711499708:ios:cc30d5521b4be487b631b9',
    messagingSenderId: '802711499708',
    projectId: 'automotrizapp',
    databaseURL: 'https://automotrizapp-default-rtdb.firebaseio.com',
    storageBucket: 'automotrizapp.firebasestorage.app',
    iosBundleId: 'com.example.obdv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2PZG1yBdKgs6j6sEFV9CIxMYak_2T7q8',
    appId: '1:802711499708:ios:cc30d5521b4be487b631b9',
    messagingSenderId: '802711499708',
    projectId: 'automotrizapp',
    databaseURL: 'https://automotrizapp-default-rtdb.firebaseio.com',
    storageBucket: 'automotrizapp.firebasestorage.app',
    iosBundleId: 'com.example.obdv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8_gnkchNhFJRSlciwl-25nERVhA0xO8',
    appId: '1:802711499708:web:4efeb408215328d2b631b9',
    messagingSenderId: '802711499708',
    projectId: 'automotrizapp',
    authDomain: 'automotrizapp.firebaseapp.com',
    databaseURL: 'https://automotrizapp-default-rtdb.firebaseio.com',
    storageBucket: 'automotrizapp.firebasestorage.app',
    measurementId: 'G-M5111MPZDQ',
  );

}