// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEfi4pfxgxbZCmOZnOQA8P-GRBtPHT3sw',
    appId: '1:496119517970:web:e1f6372d42f9c5624b19cb',
    messagingSenderId: '496119517970',
    projectId: 'automotrizprueba',
    authDomain: 'automotrizprueba.firebaseapp.com',
    storageBucket: 'automotrizprueba.firebasestorage.app',
    measurementId: 'G-TJD96MKMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAsMl4rl4d5iCFXtV_CHCHWXogx8_k7ms',
    appId: '1:496119517970:android:d7eb0c24052712064b19cb',
    messagingSenderId: '496119517970',
    projectId: 'automotrizprueba',
    storageBucket: 'automotrizprueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4zGFbRiRQ9IPI0s3_2FltD1YI-jVUbHM',
    appId: '1:496119517970:ios:4a4b0468042a30084b19cb',
    messagingSenderId: '496119517970',
    projectId: 'automotrizprueba',
    storageBucket: 'automotrizprueba.firebasestorage.app',
    iosClientId: '496119517970-d0su6o60ocfdaseodumhkpidh553v79a.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4zGFbRiRQ9IPI0s3_2FltD1YI-jVUbHM',
    appId: '1:496119517970:ios:4a4b0468042a30084b19cb',
    messagingSenderId: '496119517970',
    projectId: 'automotrizprueba',
    storageBucket: 'automotrizprueba.firebasestorage.app',
    iosClientId: '496119517970-d0su6o60ocfdaseodumhkpidh553v79a.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoAuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEfi4pfxgxbZCmOZnOQA8P-GRBtPHT3sw',
    appId: '1:496119517970:web:6c1b0d3987f9fd544b19cb',
    messagingSenderId: '496119517970',
    projectId: 'automotrizprueba',
    authDomain: 'automotrizprueba.firebaseapp.com',
    storageBucket: 'automotrizprueba.firebasestorage.app',
    measurementId: 'G-7FCRVM61R4',
  );
}
